sudo: required
services:
  - docker

before_install:
  - docker build -t yuyaito3/docker-nginx -f ./client/Dockerfile.dev ./client

script:
  - docker run yuyaito3/docker-nginx npm test -- --coverage

after_success:
  - docker build -t yuyaito3/multi-client ./client
  - docker build -t yuyaito3/multi-nginx ./nginx
  - docker build -t yuyaito3/multi-server ./server
  - docker build -t yuyaito3/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yuyaito3/multi-client
  - docker push yuyaito3/multi-nginx
  - docker push yuyaito3/multi-server
  - docker push yuyaito3/multi-worker